# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 247eb0fda74c803dc23e95720f8bd75bc01179ccebce5aa3188ba9698d438af634fff95be8b244847bea91496e20fa473662f723934139bac8bc48a62f6d32a4

test:
  secret_key_base: e4e4276df20657348e9857dd80a137156aaacfd6d728c2dd0d7e2371fadb8b8c7926cd5adbcdda131f8714491b7a4dd64148b1741e571798533f58762c4c5136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
